title: TYPEMILL
author: Unknown
copyright: ©
year: '2018'
theme: typemill
startpage: true
plugins:
    admin:
        active: false
    analytics:
        piwik_url: ''
        piwik_id: ''
        google_id: ''
        active: false
    cookieconsent:
        theme: edgeless
        position: bottom
        message: 'This website uses cookies to ensure you get the best experience on our website.'
        link: 'Learn More'
        dismiss: 'Got It'
        popup_background: '#70c1b3'
        popup_text: '#ffffff'
        button_background: '#66b0a3'
        button_text: '#ffffff'
        active: false
    demo:
        theme: edgeless
        message: 'You can enter a message here.'
        website: 'http://typemill.net'
        background: '#ffffff'
        SimpleCheckbox: 'on'
        date: ''
        active: false
    disqus:
        shortname: ''
        active: false
    finalwords:
        active: 'on'
    version:
        active: false
    share:
        active: true
latestVersion: 1.1.1
